# Package Overview
package_name: gbm_model

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (sale price)
target: Attrition_Flag


pipeline_name: gbm_model
pipeline_save_file: gbm_model_output_v


features:
  - Customer_Age
  - Gender
  - Dependent_count
  - Education_Level
  - Marital_Status
  - Income_Category
  - Card_Category
  - Months_on_book
  - Total_Relationship_Count
  - Months_Inactive_12_mon
  - Contacts_Count_12_mon
  - Credit_Limit
  - Total_Revolving_Bal
  - Avg_Open_To_Buy
  - Total_Amt_Chng_Q4_Q1
  - Total_Trans_Amt
  - Total_Trans_Ct
  - Total_Ct_Chng_Q4_Q1
  - Avg_Utilization_Ratio

# set train/test split
test_size: 0.2

# to set the random seed
random_state: 0

# to set n_neighbors for oversampling (ADASYN)
n_neighbors: 5

# to set params for gbm model
n_estimators: 658
criterion: 'friedman_mse'
max_depth: 5
min_samples_split: 0.017209668061883378
max_features: 'sqrt'
learning_rate: 0.050497537295197764


# variables to map
categorical_vars:
  - Gender
  - Education_Level
  - Marital_Status
  - Income_Category
  - Card_Category
  
